# awsへのdeploy
# 
name: AWS Lambda Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: get-caller-identity is allowed to run on role.
      run: aws sts get-caller-identity

    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip3 install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip3 install -r requirements.txt --no-deps --target ./package

    - name: Copy lambda_function.py to package directory
      run: cp lambda_function.py ./package

    - name: Create deployment package
      run: |
        cd package
        zip -r9 ${OLDPWD}/function.zip .

    - name: Upload deployment package
      run: |
        aws lambda update-function-code \
          --function-name ChatBotFunction \
          --zip-file fileb://function.zip \
          --publish
